---
- name: Remove pre-installed PostgreSQL versions
  apt:
    name: postgresql
    state: absent

- name: Install PostgreSQL
  become: true
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2

- name: Start Postgres
  become: true
  command: systemctl start postgresql

- become: true
  become_user: postgres
  block:
    - name: Get postgres processes
      shell: "ps aux |grep postgres"
      register: potgres_processes

    - name: Print postgres processess
      debug:
        msg: "{{ potgres_processes.stdout }}"

    - name: Get postgres versions
      shell: "ls /usr/lib/postgresql"
      register: potgres_versions

    - name: Print postgres versions
      debug:
        msg: "{{ potgres_versions.stdout }}"

    - name: Get PostgreSQL client version
      shell: "psql --version"
      register: psql_client_version
      
    - name: Print PostgreSQL client version
      debug:
        msg: "Using PostgreSQL {{ psql_client_version.stdout }}"

    - name: Create PostgreSQL database
      postgresql_db:
        name: "{{ database_name }}"

    - name: Create PostgreSQL users
      postgresql_user:
        name: "{{ database_user }}"
        password: "{{ database_password }}"
        db: "{{ database_name }}"
        encrypted: yes
        priv: ALL

    - name: Add PostgreSQL extensions
      postgresql_ext:
        name: "{{ item }}"
        db: "{{database_name}}"
      with_items:
        - plpgsql
        - unaccent
        - pg_trgm
