---
- name: Install gems (this may take a few minutes)
  shell: "source /home/{{ deploy_user }}/.rvm/scripts/rvm && bundle install --path {{ shared_dir }}/bundle --without development test"
  args:
    chdir: "{{ release_dir }}"
    executable: /bin/bash

- name: Copy secrets configuration to shared folder
  copy:
    src: "{{ release_dir }}/config/secrets.yml.example"
    dest: "{{ shared_dir }}/config/secrets.yml"
    remote_src: yes
    force: no

- name: Copy database configuration to shared folder
  template:
    src: "{{ playbook_dir }}/roles/rails/templates/database.yml"
    dest: "{{ shared_dir }}/config/database.yml"
    force: no

- name: Add symbolic links for secrets and database configuration
  file:
    state: "link"
    src: "{{ shared_dir }}/config/{{ item }}"
    dest: "{{ release_dir }}/config/{{ item }}"
  with_items:
    - "secrets.yml"
    - "database.yml"

- name: Update host configuration in secrets.yml
  lineinfile:
    path: "{{ release_dir }}/config/secrets.yml"
    regexp: 'server_name'
    line: '  server_name: "{{ server_hostname }}"'

- name: Generate secret key
  shell: "source {{ home_dir }}/.rvm/scripts/rvm && bin/rake secret"
  register: secret_key_base
  args:
    chdir: "{{ release_dir }}"
    executable: /bin/bash

- name: Update secret_key_base configuration in secrets.yml
  replace:
    path: "{{ shared_dir }}/config/secrets.yml"
    regexp: '^{{ env }}:\n  secret_key_base: ""'
    replace: '{{ env }}:\n  secret_key_base: "{{ secret_key_base.stdout }}"'

- name: Force https connection
  lineinfile:
    path: "{{ release_dir }}/config/environments/{{ env }}.rb"
    regexp: "force_ssl"
    line: "  config.force_ssl = true"
  when: domain is defined

- name: Do not force https connection
  lineinfile:
    path: "{{ release_dir }}/config/environments/{{ env }}.rb"
    regexp: "force_ssl"
    line: "  config.force_ssl = false"
  when: domain is not defined

- name: Create Database
  shell: "source /home/{{ deploy_user }}/.rvm/scripts/rvm && bin/rake db:migrate RAILS_ENV={{ env }}"
  args:
    chdir: "{{ release_dir }}"
    executable: /bin/bash

- name: Load configuration seeds
  shell: "source /home/{{ deploy_user}}/.rvm/scripts/rvm && bin/rake db:seed RAILS_ENV={{ env }}"
  args:
    chdir: "{{ release_dir }}"
    executable: /bin/bash

- name: Precompile assets
  shell: "source /home/{{ deploy_user }}/.rvm/scripts/rvm && bin/rake assets:precompile RAILS_ENV={{ env }}"
  args:
    chdir: "{{ release_dir }}"
    executable: /bin/bash
