name: Test suite
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        rails_env: [staging, production]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Ansible
        run: pip install ansible
      - name: Update system packages
        run: sudo apt-get update -y
      - name: Install OpenSSH
        run: sudo apt-get install -y openssh-server
      - name: Generate dummy SSH key
        run: ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
      - name: Create hosts file
        run: echo "localhost ansible_connection=local ansible_user=root" > hosts
      - name: Run CONSUL installer
        run: ansible-playbook consul.yml -i hosts --extra-vars "env=${{ matrix.rails_env }} domain=localhost errbit=True" -vvv
